### ISSUE TITLE
Would you have any plans to release code

### ISSUE THREAD

**Issue by haowang1992** [wenjiaXu/APN-ZSL#1]
Hi, congratulations on your work on NeurIPS! Would you have any plans to release the code?

**Comment by zlbuaa** [comment]
Hi, I have implemented your method based on the paper. However, the performance on CUB for GZSL can only reach about 60 for the harmonic mean. Are there any tricks or other details not mentioned in the paper?

**Comment by wenjiaXu** [comment]
Hi, I have released the code :)
