### ISSUE TITLE
About heatmap

### ISSUE THREAD

**Issue by NanAlbert** [wenjiaXu/APN-ZSL#14]
您好，我根据您的其他解答“APN-ZSL/model/model_proto.py 第154行return了attention，对于每一张图片，会输出312个attribute attention map，大小是7*7。经过bicubic interpolation之后就可以使用。” 对attention进行可视化，大部分 attention 都关注到目标的整体。不知道是自己实现有问题，还是说的确存在这样趋于关注整体的结果。麻烦您的解答，非常感谢。
![test_1_att88](https://user-images.githubusercontent.com/36076117/148003991-caa77d89-8105-40ef-a47c-6994a135848f.png)

**Comment by wenjiaXu** [comment]
> 您好，我根据您的其他解答“APN-ZSL/model/model_proto.py 第154行return了attention，对于每一张图片，会输出312个attribute attention map，大小是7*7。经过bicubic interpolation之后就可以使用。”

听起来这样可视化没有问题。

> 对attention进行可视化，大部分 attention 都关注到目标的整体。不知道是自己实现有问题，还是说的确存在这样趋于关注整体的结果。麻烦您的解答，非常感谢。 ![test_1_att88](https://user-images.githubusercontent.com/36076117/148003991-caa77d89-8105-40ef-a47c-6994a135848f.png)

在我的观察里，可能一小部分图片的attribute attention关注到目标的整体，通常发生在较小的鸟类身上（如麻雀），但如图中的海鸟，一般来说attention map能够关注到头部、腹部、橙色的腿等不同的部位。所以我不太清楚您的问题出在哪里，您试一下比较第一个epoch和第10个epoch的attention，看有没有变化？
