### ISSUE TITLE
about sun dataset

### ISSUE THREAD

**Issue by BigHyf** [wenjiaXu/APN-ZSL#15]
hello,i want to know how to download sun dataset,i only see sun397 and sun2012,but either of them are not matched.

**Comment by wenjiaXu** [comment]
Hi, the SUN dataset is downloaded from this link https://cs.brown.edu/~gmpatter/sunattributes.html.
The reference paper is “Sun attribute database: Discovering, annotating, and recognizing scene attributes,” in CVPR, 2012.

**Comment by wenjiaXu** [comment]
> hello,i want to know how to download sun dataset,i only see sun397 and sun2012,but either of them are not matched.

Hi, the SUN dataset is downloaded from this link https://cs.brown.edu/~gmpatter/sunattributes.html.
The reference paper is “Sun attribute database: Discovering, annotating, and recognizing scene attributes,” in CVPR, 2012.
