### ISSUE TITLE
Question about the implementation.

### ISSUE THREAD

**Issue by zlbuaa** [wenjiaXu/APN-ZSL#2]
Hi, I have implemented your method based on the paper. However, the performance on CUB for GZSL can only reach about 60 for the harmonic mean. Are there any tricks or other details not mentioned in the paper?

**Comment by wenjiaXu** [comment]
Hi, have you used Calibrated Stacking [7] as stated in the paper? With Calibrated Stacking, we can boost GZSL accuracy for a large margin. Please check section 3.3 for more details.
