### ISSUE TITLE
Are attributes normalized?

### ISSUE THREAD

**Issue by utkarshmall13** [wenjiaXu/APN-ZSL#7]
Hi, are the attributes vectors l2 normalized when implementing the two branches (like in the prior work Xian et. al. prior work)? 
Also, when is the code releasing, I'm finding it hard to reproduce the results with my implementation.

**Comment by hawklucky** [comment]
I have the same question for more detailed implementation, as the reproduction is unsuccessful.

**Comment by utkarshmall13** [comment]
@hawklucky may I ask what ZSL or GZSL accuracy are you getting on CUB just to check if my implementation is somewhat correct?

**Comment by wenjiaXu** [comment]
We used the same attributes vectors as Xian did in his TPAMI paper, and the code is released now :)
